server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=30s ipv6=off;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Static frontend routing for Single Page Application
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy to vacancy-service (Port 8082 - Member 2)
    location /api/vacancies {
        set $upstream_vacancy vacancy-service;
        proxy_pass http://$upstream_vacancy:8082$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy to matching-service (Port 8083 - Member 3)
    location /api/matches {
        set $upstream_matching matching-service;
        proxy_pass http://$upstream_matching:8083$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/notifications {
        set $upstream_matching matching-service;
        proxy_pass http://$upstream_matching:8083$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy to user-service (Port 8081 - Member 1) for /api/auth, /api/workers, /api/hr
    location /api/ {
        set $upstream_user user-service;
        proxy_pass http://$upstream_user:8081$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
