spring.application.name=user-service

server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:PT1H}
security.hr-registration-key=${HR_REGISTRATION_KEY}
